### PR TITLE
[WIP] Add mailing support

### LINKED ISSUE #8: Send an email when a job failed
When a job fails after all available retries, send an email to selected recipients to inform them of the failure

Allow configuration of recipients in the configuration file on a per-job basis, but also allow to override it when queing jobs for single runs using ZMQ.

### PR DESCRIPTION
**Pull request by kbariotis**
This is my attempt to resolve #8 and its still a WIP.

I would love to hear your thoughts on the configuration part cause Im really not sure this is the way to go.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -47,6 +49,11 @@ export default class Dispo {
     this._logger = new Logger(this.config.options.logging)
     this._logger.init()
 
+    if (this.config.options.mailer.enabled) {
```
Comment (codepunkt) [inline src/index.js]: It is possible that someone has a config like this, in which case the if statement fails.

``` json
{ "options": { "mailer": null } }
```

I suggest also checking the existence/truthiness of `this.config.options.mailer`.

File: src/index.js [hunk 2]
```diff
@@ -87,18 +94,37 @@ export default class Dispo {
...
+  async _handleFailed (id, msg) {
+    await this._mailer.sendMail(id)
+    await this._logger.logFailure(id, msg)
+  }
+
+  async _handleComplete (id) {
+    await this._logger.logComplete(id)
+  }
+
+  async _handleCompleteAlways (id) {
```
Comment (codepunkt) [inline src/index.js:146]: Not sure about the naming of this method. Could not find a better one that i really liked otoh though :)

File: src/index.js [hunk 3]
```diff
@@ -87,18 +94,37 @@ export default class Dispo {
     this._queue.watchStuckJobs(5e3)
 
     if (NODE_ENV !== 'test') {
-      this._queue.on('job start', async (id) => await this._logger.logStart(id))
-      this._queue.on('job failed attempt', async (id, msg) => await this._logger.logFailedAttempt(id, msg))
-      this._queue.on('job failed', async (id, msg) => await this._logger.logFailure(id, msg))
-      this._queue.on('job complete', async (id) => await this._logger.logComplete(id))
+      this._queue.on('job start', async (id) => await this._handleStart(id))
```
Comment (codepunkt) [inline src/index.js:118]: Extracting or not extracting all these methods was largely a matter of choice before. Now that there are at least 2 event handlers that do more than simply logging
- the complete one that always runs to requeue when defined as a cron
- the failed one sending mail if configured to do so

So i think its a good choice to do this here!

File: src/mailer.js [hunk 4]
```diff
@@ -0,0 +1,49 @@
+import nodemailer from 'nodemailer'
+import { getJob } from '.'
+
+/**
+ * Default logger options
+ * @type {Object}
+ */
+const defaults = {
+  nodemailerConfig: {
+    transportOptions: null,
```
Comment (codepunkt) [inline src/mailer.js:11]: Looks good to me. I think there is a default transportOption we could pursue and add to this project so you don't have to have an smtp server at hand and can simply use this feature by enabling the email option and adding email addresses to the jobs configuration: the `nodemailer-sendmail-transport` package which uses sendmail under the hood.

Also, overriding the `to` property based on the email address(es) given in the jobs config file is an important one. When doing so and parsing this somewhere in `parseJobs`, tests for parseJobs should be updated to reflect this change as well.

@Draggha had to do something like this in his PR for incremental backoff - he added an additional utility method to do the configuration parsing for that which is called inside `parseJobs` and has its own tests. I like that idea/general direction :)

**Review by codepunkt — COMMENTED** [review]
Good job. I know its a WIP and hope i can give a little bit of guidance/direction with my comments.

I'm also going to merge #9 by @Draggha tomorrow, so you might have some merging to do based on that later on.

**Comment by kbariotis** [comment]
@gonsfx Thank you so much. I have updated the PR.

File: src/mailer.js (hunk 4 above)
Comment (kbariotis) [reply src/mailer.js:11]: I see. I could rebase my PR when #9 is merged.

**Comment by codepunkt** [comment]
@kbariotis looking good. please resolve the conflicts and then i'm up for merging it in 👍

File: README.md [hunk 5]
```diff
@@ -55,8 +57,12 @@ The `attempts` property on the database cleanup job defines that the job is only
...
       "file": "jobs/databaseCleanup.js",
       "cron": "0 1 * * * *",
-      "attempts": 1
+      "attempts": 1,
+      "recipients": "example@email.com"
     }
   }
 }
 ```
+
```
Comment (codepunkt) [inline README.md:66]: Nice documentation

File: src/index.js [hunk 6]
```diff
@@ -47,6 +49,12 @@ export default class Dispo {
     this._logger = new Logger(this.config.options.logging)
     this._logger.init()
 
+    if ('enabled' in this.config.options.mailer &&
```
Comment (codepunkt) [inline src/index.js]: This can still crash when someone defines `{ mailer: null }`.
I suggest simply testing for truthiness:

``` javascript
if (this.config.options.mailer && this.config.options.mailer.enabled) {
 // init mailer
}
```

**Review by codepunkt — COMMENTED** [review]
I've added a few review comments - but in the grand scheme of things, this looks good. I might change a few minor things afterwards, but you did a really good job here :)

**Comment by kbariotis** [comment]
Comments and merge conflicts resolved. Thank you @gonsfx

**Comment by codepunkt** [comment]
@kbariotis Thank you for helping out! 👍
